version: "3.9"
services:
  database:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "social_network_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - database
    ports:
      - "5000:80"