version: "3.9"
services:
  database:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "social_network_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      ports: "5432:5432"
      networks: mynetwork
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - database
    depends_on:
      - database
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge